#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()
usage = dbus.Interface(bus.get_object('org.freesmartphone.ousaged', '/org/freesmartphone/Usage'),
                       'org.freesmartphone.Usage')

resources = usage.ListResources()

if sys.argv[1] in resources:
    usage.SetResourcePolicy(sys.argv[1], 'disabled')
else:
    print "ERROR: resource %s is not available" % sys.argv[1]
