#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()
usage = dbus.Interface(bus.get_object('org.freesmartphone.ousaged', '/org/freesmartphone/Usage'),
                       'org.freesmartphone.Usage')

resources = usage.ListResources()

n = 0
for r in resources:
    state = usage.GetResourcePolicy(r)
    print "%i: %s %s" % (n, r, state)
    n += 1
